name: taylordiff
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jax
  - jaxlib
  - flax
  - optax
  - numpy
  - matplotlib
  - pyyaml
  - tqdm
  - pip:
    - wandb
    - transformers
    - datasets